# Generated by Django 3.1.2 on 2021-01-15 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/youtubers/%Y/%m/')),
                ('videourl', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('camera_type', models.CharField(max_length=50)),
                ('subs_count', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('isfeatured', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
